version: "3.8"

networks:
    spick-net:
        driver: bridge

services:
    notification-app:
        platform: linux/amd64
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - spick-net
        ports:
            - "8002:8002"
