version: "3.8"

networks:
  spick-net:
    driver: bridge
    external: true

services:
  authentication:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - spick-net
    ports:
      - "8103:8103"