volumes:
  rabbitmq_data: 
  user_schedule_data: 

networks:
  schedula:
    driver: bridge
    name: schedula

services:

  #######################################
  # Rabbit MQ
  #######################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - schedula

  #######################################
  # User_schedule Microservice
  #######################################
  user_schedule:
    build: 
      context: .\simple_services\user_schedule
      dockerfile: dockerfile
    restart: always
    ports:
      - "8007:8007"
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/user_schedule
      PYTHONUNBUFFERED: 1
    networks:
      - schedula
    volumes: 
      - user_schedule_data: /var/lib/mysql

  #######################################
  # Optimizer Microservice
  #######################################
  optimizer:
    build: 
      context: .\simple_services\optimizer
      dockerfile: dockerfile
    restart: always
    ports:
      - "8008:8008"
    networks:
      - schedula
    
        

