_format_version: "1.1"

services:
  - name: authentication-service
    url: http://authentication:8103
    routes:
      - name: signup-route
        paths:
          - /api/v1/signup
        methods:
          - POST
      - name: login-route
        paths:
          - /api/v1/login
        methods:
          - POST
          
  # - name: event-service
  #   url: http://localhost:8100
  #   routes:
  #     - name:
  #       paths:
  #         -
  #       methods:
  #         - 
  #     - name:
  #       paths:
  #         -
  #       methods:
  #         - 

# CORS plugin
plugins:
  - name: cors
    config:
      origins:
        - '*'