version: "3.8"

networks:
    spick:
        driver: bridge

services:
    event-mysql:
        platform: linux/amd64
        networks:
            - spick
        image: event-mysql
        build: ./mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_PASSWORD: false
        ports:
            - "3308:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p root"]
            interval: 30s
            timeout: 5s
            retries: 10

    event:
        platform: linux/amd64
        build: .

        networks:
            - spick
        env_file:
            - .env
        ports:
            - "8000:8000"
        depends_on:
            event-mysql:
                condition: service_healthy
